export const videos = [
  {
    id: "video-001",
    title: "I Built a Tiny Music Studio in My Closet",
    creator: "Maya Makes Noise",
    subscribers: "42K subscribers",
    views: "128K views",
    uploaded: "2 days ago",
    duration: "12:18",
    category: "Music",
    eligible: true,
    art: "art-studio",
    avatar: "MM",
    avatarColor: "linear-gradient(135deg, #e78562, #5939a6)",
    description: "A shoebox room, one microphone, and a lot of acoustic foam. Here is how I made a small recording space work.",
    hypePoints: "28.4K Hype points",
  },
  {
    id: "video-002",
    title: "The Math Behind Perfect Volleyball Serves",
    creator: "Second Contact",
    subscribers: "18K subscribers",
    views: "74K views",
    uploaded: "4 days ago",
    duration: "8:41",
    category: "All",
    eligible: true,
    art: "art-volleyball",
    avatar: "SC",
    avatarColor: "linear-gradient(135deg, #52c4dd, #2845a1)",
    description: "We broke down the angles, spin, and timing behind a serve that keeps landing exactly where you want it.",
    hypePoints: "16.8K Hype points",
  },
  {
    id: "video-003",
    title: "Why Old Cameras Feel Better",
    creator: "Frame by Frame",
    subscribers: "620K subscribers",
    views: "201K views",
    uploaded: "1 day ago",
    duration: "15:06",
    category: "All",
    eligible: false,
    art: "art-camera",
    avatar: "FF",
    avatarColor: "linear-gradient(135deg, #d8c57b, #6e3f22)",
    description: "A love letter to old viewfinders, tiny mechanical shutters, and the patience of shooting one frame at a time.",
    hypePoints: "Not Hype eligible",
  },
  {
    id: "video-004",
    title: "Building a City Under the Ocean",
    creator: "Block Theory",
    subscribers: "126K subscribers",
    views: "96K views",
    uploaded: "6 days ago",
    duration: "18:22",
    category: "Gaming",
    eligible: true,
    art: "art-ocean",
    avatar: "BT",
    avatarColor: "linear-gradient(135deg, #48d5c3, #1a3b87)",
    description: "This underwater city took a month to plan. Today, the transit system finally connects every dome.",
    hypePoints: "11.2K Hype points",
  },
  {
    id: "video-005",
    title: "The One Sound That Makes a Song Feel Huge",
    creator: "Amber Room Audio",
    subscribers: "63K subscribers",
    views: "55K views",
    uploaded: "5 days ago",
    duration: "9:14",
    category: "Music",
    eligible: true,
    art: "art-sound",
    avatar: "AR",
    avatarColor: "linear-gradient(135deg, #f0b061, #914ca7)",
    description: "A practical arrangement trick you can use in any genre, whether you are producing at home or in a studio.",
    hypePoints: "9.6K Hype points",
  },
];

export const getVideo = (id) => videos.find((video) => video.id === id);
